- Switch the default root volume for EC2 images from gp2
SUSE-Enceladus/mash pull request #726
Opened 2020-12-12 13:34 UTC by rjschwei

(ssd) to   the new gp3 volume type. This affords users a 20% cost saving
  with no penalties. Requires ec2imgutils 9.0.1 or greater.

### What does this PR do? Why are we making this change?

### How will these changes be tested?

### How will this change be deployed? Any special considerations?

### Additional Information

2020-12-15 16:12 UTC, jgleissner approved these changes

2020-12-15 16:34 UTC, smarlowucf requested changes
Also, want to update the .virtualenv.requirements.txt.

2020-12-15 16:34 UTC, smarlowucf commented on package/mash.spec
> +BuildRequires:  python3-ec2imgutils >= 9.0.1
There's also a requires clause.

2020-12-15 16:35 UTC, smarlowucf commented
The check failure is from OCI. Will submit a separate PR to fix this.

2020-12-15 21:29 UTC, smarlowucf commented
Re-based to confirm build.

2020-12-16 14:48 UTC, smarlowucf approved these changes

2020-12-16 14:54 UTC, merged