And add routes, utils and schema
SUSE-Enceladus/mash pull request #750
Opened 2021-03-16 18:09 UTC by smarlowucf

For Aliyun jobs in the API service.

### What does this PR do? Why are we making this change?

### How will these changes be tested?

### How will this change be deployed? Any special considerations?

### Additional Information

2021-03-16 18:12 UTC, smarlowucf commented
Relies on #749

2021-03-17 07:59 UTC, jgleissner approved these changes

2021-03-17 11:25 UTC, rjschwei requested changes

2021-03-17 11:25 UTC, rjschwei commented on mash/services/api/schema/jobs/aliyun.py
> +    'HIDDEN',
s/HIDDEN/FOO/

Since we couldn't find any docs about the valid settings we should treat this as semi-secret.

2021-03-17 13:09 UTC, smarlowucf commented on mash/services/api/schema/jobs/aliyun.py
> +    'HIDDEN',
rebased to cleanup the example.

2021-03-17 13:09 UTC, smarlowucf commented
Will wait for #749 to rebase and merge and ensure tests pass.

2021-03-17 22:00 UTC, rjschwei approved these changes

2021-03-29 21:39 UTC, merged