Add a slow rollout policy to new GCE images.
SUSE-Enceladus/mash pull request #780
Opened 2021-06-21 18:27 UTC by illfelder

### What does this PR do? Why are we making this change?
Introduce slow rollout policy for new GCE image publication and deprecation.

### How will these changes be tested?
TBD (Please help me figure out how to test these changes work in your build environment).

### How will this change be deployed? Any special considerations?
These changes should be used whenever publishing new images in GCE. No action should be required to use these new changes.

### Additional Information
Existing usage of the API should behave as normal and without change.

2021-06-25 17:02 UTC, illfelder commented
@rjschwei - can you please loop in someone to take a look?

2021-06-26 01:08 UTC, smarlowucf commented
Hi @illfelder I will take a look but it will be sometime next week at the earliest.

2021-07-01 15:58 UTC, smarlowucf requested changes

2021-07-01 15:58 UTC, smarlowucf commented on mash/utils/gce.py
> -        kwargs['family'] = family
We don't always include family. For example when testing.

2021-07-01 15:58 UTC, smarlowucf commented on mash/services/deprecate/gce_job.py
> +            compute_driver = get_gce_compute_driver(credential, version='alpha')
Does alpha rely on a specific SDK version? We are using distribution packages instead of PyPI so we aren't pulling in latest versions as they release.

2021-07-01 15:58 UTC, smarlowucf commented on mash/utils/gce.py
> +    zones = sorted(zones.get('items'), key=lambda zone: zone.get('name'))
Why are zones sorted only to be shuffled later?

2021-07-01 15:58 UTC, smarlowucf commented on mash/utils/gce.py
> +        zones_map.setdefault(region, []).append(name)
We are going through a list of zones then re-packing them into a list for their respective regions. Can't we just go through a list of regions and pull a list of zones? I realize the performance difference probably isn't that much but I think it would make the function more readable.

2021-07-01 15:58 UTC, smarlowucf commented on mash/utils/gce.py
> +    return [
Is there a way to do this that's more readable?

2021-07-01 15:58 UTC, smarlowucf commented on mash/utils/gce.py
> +    zones = zones = get_zones(compute_driver, project)
Typo s/zones = zones =/zones =

2021-07-01 16:04 UTC, smarlowucf commented
Please sign all the commits. See the GitHub docs for more info on signing commits and setting up a gpg key if necessary. https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits

2021-07-01 16:06 UTC, illfelder commented on mash/utils/gce.py
> -        kwargs['family'] = family
Fields that are not set will be None which is ignored by the API.

2021-07-01 16:08 UTC, illfelder commented on mash/services/deprecate/gce_job.py
> +            compute_driver = get_gce_compute_driver(credential, version='alpha')
It shouldn't, but if you run into issues let me know.

2021-07-01 16:09 UTC, illfelder commented on mash/utils/gce.py
> +    zones = sorted(zones.get('items'), key=lambda zone: zone.get('name'))
The zones are sorted, the regions are shuffled. This logic will always roll out `us-central1-a` before `us-central1-f`, but `us-central1` and `us-west1` have no predetermined ordering.

2021-07-01 16:11 UTC, illfelder commented on mash/utils/gce.py
> +        zones_map.setdefault(region, []).append(name)
We wanted the zones ordering to be deterministic so that we know `-a` will roll out before `-b`.

2021-07-01 16:12 UTC, illfelder commented on mash/utils/gce.py
> +    zones = zones = get_zones(compute_driver, project)
Thanks for catching this!

2021-07-01 17:12 UTC, illfelder commented on mash/utils/gce.py
> +    return [
It can be done in other ways, but I wouldn't consider them more readable. I added comments explaining the logic though.

2021-07-02 18:33 UTC, smarlowucf commented on mash/utils/gce.py
> +        zones_map.setdefault(region, []).append(name)
If you get a list of regions, are the zones preloaded or lazy loaded when you call the zones attr on a region? I ask because it seems there's a significant difference in requests in each route.

The current implementation would have 1 request to get all zones then a request for every zone to get it's respective region. Whereas getting a list of regions, if the zones are preloaded is a single request.

2021-07-02 18:34 UTC, smarlowucf commented on mash/utils/gce.py
> +    return [
Thanks for the comments. The itertools part is still quite confusing to me and I think that would be the same for anyone else who comes along the code in the future. Without digging up documentation for itertools I don't understand what the return type is. What does the output look like that's returned?

2021-07-02 19:32 UTC, smarlowucf commented
E2E testing is difficult. I think only we can do that unless you want to manually create a pipeline for testing. The unit tests and formatting checks would be next. All code has tests `pytest --cov=mash` and has no formatting errors `flake8 mash tests`.

2021-07-02 19:47 UTC, smarlowucf commented on mash/utils/gce.py
> +    return [
I pulled the code out to follow logic so I understand the output now. This is confusing because it starts as a list of lists and the comment:

`Interleave varying sized lists of zones adding a 'zones/' prefix.`

Is a bit vague. To me it seemed like the end result was still a list of lists. Part of the confusion is because the format string contains `zones/%s` has a connotation of multiple not singular. I understand the difficulty of writing this in another way but if the different steps were split out into separate lines with more clear explanation on what's happening I think it will be more readable.

2021-07-02 19:49 UTC, smarlowucf commented on mash/utils/gce.py
> +        'zones/%s' % zone for zone in itertools.chain(
I missed this the first time through. Can we switch to the `.format` style here? I realize it's a code style thing but I've tried to remove any of the old style `%s` formatting from the codebase.

2021-07-02 19:50 UTC, smarlowucf commented on mash/utils/gce.py
> +        'zones/%s' % zone for zone in itertools.chain(
Unfortunately we cannot do f' strings yet to support older python versions.

2021-07-02 22:54 UTC, illfelder commented on mash/utils/gce.py
> +        'zones/%s' % zone for zone in itertools.chain(
Updated.

2021-07-02 22:55 UTC, illfelder commented on mash/utils/gce.py
> +    return [
Can you take a look at the most recent version where I give examples of what each step should look like?

2021-07-07 15:45 UTC, smarlowucf commented
Looks good. Next items would be testing,formatting then E2E tests.

- pytest --cov=mash (passing plus full coverage)
- flake8 mash tests (no errors)
- E2E testing with production setup

2021-07-08 17:55 UTC, illfelder commented
- The pytest coverage hasn't changed (still 100% for everything).
- flake8 identified an import issue that I addressed and is now clean.

2021-07-08 18:04 UTC, illfelder commented
Issue I'm encountering while trying to run pytest. I verified all dev requirements are installed.
```
pytest --cov=mash
============================================================================ test session starts ============================================================================
platform linux -- Python 3.9.2, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /usr/local/google/home/illfelder/cloud/mash, configfile: setup.cfg
plugins: cov-2.12.1
collected 0 items / 1 error                                                                                                                                                 
Coverage.py warning: Module mash was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
WARNING: Failed to generate report: No data to report.

/usr/local/google/home/illfelder/.local/lib/python3.9/site-packages/pytest_cov/plugin.py:271: PytestWarning: Failed to generate report: No data to report.

  self.cov_controller.finish()

================================================================================== ERRORS ===================================================================================
_______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
../../../../.local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
services/api/conftest.py:3: in <module>
    from mash.services.api.app import create_app
E   ModuleNotFoundError: No module named 'mash'

----------- coverage: platform linux, python 3.9.2-final-0 -----------

========================================================================== short test summary info ==========================================================================
ERROR ../.. - ModuleNotFoundError: No module named 'mash'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.14s ==============================================================================
```

2021-07-14 13:39 UTC, smarlowucf commented
To get pytest to work properly you should be able to install mash as editable with the following:

`pip install -e .`

And to get the dev requirements:

`pip install -r .virtualenv.dev-requirements.txt`

2021-07-14 16:44 UTC, illfelder commented
Thank you. that did the trick! I've updated tests and they now fully pass.

2021-07-14 21:30 UTC, smarlowucf commented
Great! Looks good. The last piece is to get coverage on the new `get_zones` and `create_gce_rollout` functions. Note that the tests require manually mocking the GCE API calls so they run consistently without network connection.

`pytest --cov=mash --cov-report=term-missing`

2021-07-14 21:33 UTC, smarlowucf approved these changes

2021-07-14 22:42 UTC, illfelder commented
Additional test coverage added. Thanks for the command!

2021-07-26 16:19 UTC, smarlowucf commented
I tested this successfully with api client == 1.8.0 and in production we have 1.7.4. As far as I can tell there's no breaking changes between 1.8.0 and 1.7.4 so this should be good to merge.

2021-07-26 16:25 UTC, smarlowucf commented
Thanks for the contribution @illfelder :+1: , much appreciated. This will go out with the next release.

2021-07-26 16:25 UTC, merged