Modifies s3bucket upload service to allow raw image upload to a S3 bucket
SUSE-Enceladus/mash pull request #848
Opened 2023-02-27 12:06 UTC by apozsuse

### What does this PR do? Why are we making this change?

We need to have to have the possibility of just uploading raw images to a s3 bucket (without image publication)

These changes:
- Allows to use the s3upload service without `cloud_image_name` parameter (and without image publication)
- Includes the option to `use_build_time` in the `raw_image_upload_location` parameter

### How will these changes be tested?

The changes have been tested.

### How will this change be deployed? Any special considerations?

Usual procedure without special considerations.

### Additional Information
 None

2023-02-27 12:33 UTC, rjschwei approved these changes

2023-02-27 14:23 UTC, smarlowucf requested changes

2023-02-27 14:23 UTC, smarlowucf commented on .virtualenv.requirements.txt
> -flask-sqlalchemy
We can't lock into a specific version as that breaks downstream packaging. Requirements should be >= or <=.

2023-02-27 14:23 UTC, smarlowucf commented on .virtualenv.requirements.txt
> -flask-sqlalchemy
Most likely we need the <=.

2023-02-27 14:23 UTC, smarlowucf commented on mash/services/upload/s3bucket_job.py
> +            'cloud_image_name' in self.status_msg and self.status_msg[
could be simplified to  `if self.status_msg.get('cloud_image_name')`

2023-02-27 14:27 UTC, apozsuse commented on .virtualenv.requirements.txt
> -flask-sqlalchemy
OK! Had to modify the setting because the CI was failing due to an incompatibility in flask-sqlalchemy in 3.0.2
Fixed!

2023-02-27 14:28 UTC, apozsuse commented on mash/services/upload/s3bucket_job.py
> +            'cloud_image_name' in self.status_msg and self.status_msg[
There are some cases (at least in the tests) where 'cloud_image_name' is present in the dict but it has None value :S
Probably it's something just in the tests, but just in case I added the second check to validate the value is not None.

2023-02-27 14:38 UTC, smarlowucf commented on .virtualenv.requirements.txt
> -flask-sqlalchemy
If the breaking change is in 3.0.2 then I guess it probably came in 3.0.0 thus would put the conditional as < 3.0.0.

2023-02-27 15:03 UTC, apozsuse commented on mash/services/upload/s3bucket_job.py
> +            'cloud_image_name' in self.status_msg and self.status_msg[
Fixed!

2023-02-27 15:20 UTC, apozsuse commented
About the issue with the requirements.txt, finally realized that the breaking change happens in SQLAlchemy 2.0.0, so I included an explicit requirement to have a version < 2.0.0

2023-02-27 19:01 UTC, smarlowucf approved these changes
I think we only need one of the requirement pins.

2023-02-28 12:13 UTC, apozsuse commented on .virtualenv.requirements.txt
> +flask-sqlalchemy<3.0.0
Fixed!

2023-02-28 13:36 UTC, merged