WIP Small refactor in test service for ec2 to include the possibility of SEV testing
SUSE-Enceladus/mash pull request #856
Opened 2023-09-22 16:30 UTC by apozsuse

Could not finish this code change. I'll retake the job after the workshop...

2023-10-03 15:46 UTC, apozsuse commented on .virtualenv.requirements.txt
> +img-proof>=7.21.0
Included this change to assure `img-proof` has the new param.

2023-10-03 15:48 UTC, apozsuse commented on mash/services/test/ec2_job.py
> +    ],
Pending.
We'd need to check which instance_types we want to test for SEV_CAPABLE images when UEFI is supported.

2023-10-18 11:14 UTC, apozsuse commented
This one is ready for review.

2023-10-18 11:43 UTC, rjschwei commented on mash/services/test/ec2_job.py
> +                'SEV_CAPABLE' in self.guest_os_features,
'SEV_CAPABLE' is a Google setting, it is a bit confusing to see it pop up in the EC2 code stream.  Is the plan to set this in the job docs for EC2? And how is this hen documented in a sensible way for other users (not us) of mash?

2023-10-18 12:58 UTC, apozsuse commented on mash/services/test/ec2_job.py
> +                'SEV_CAPABLE' in self.guest_os_features,
Yes, the plan is to set those settings in the job docs where suitable.
I reused the Google setting names but I'm ok with changing these settings to match AWS terminology to make them more explicit:
  - I'll change 'guest_os_features' in the job doc for 'cpu_options'
  - 'SEV_CAPABLE' for 'AMD_SEV_SNP_ENABLED' 
  
WDYT?

2023-10-18 14:25 UTC, smarlowucf requested changes

2023-10-18 14:25 UTC, smarlowucf commented on mash/services/test/ec2_job.py
> +                'SEV_CAPABLE' in self.guest_os_features,
Yeah, I agree on using aws specific terminology here.

2023-10-18 14:25 UTC, smarlowucf commented on mash/services/test/ec2_job.py
> +    'us-east-1'
The feature is only available in us-east-2 and eu-west-1 regions.

2023-10-19 13:37 UTC, smarlowucf approved these changes

2023-11-01 13:18 UTC, rjschwei reviewed
I am not opposed to merging this and coming back with a follow up PR. That said, we are not in a hurry, SEV-SNP in AWS is currently broken and we need to get that fixed before we enable this testing.

2023-11-01 13:18 UTC, rjschwei commented on mash/services/test/ec2_job.py
> +                self.sev_snp_enabled = True
Come to think of it I do not think this should be a flag, i.e. true/false. We should expect TDX and we will have to test TDX instances as well. What if we change the name of the variable to `mem_encryption` with a value of  `SEV` , `TDX`, or  `NONE` and then the `select_instance_type` method can switch on that setting and either pick from `hybrid-sev-snp` (I think that could maybe simply be `sev-snp-instances`, not sure why `hybrid` is supposed to express) or the future `tdx-instances`. Then the condition can then be expressed as:
```
self.mem_encryption = 'NONE'
if info['partition'] == 'aws' and self.cloud_architecture == 'x86_64':
    if 'AMD_SEV_SNP_ENABLED' in self.cpu_options and region in sev_snp_supported_regions:
        self.mem_encryption = 'SEV'
    if 'INTEL_TDX_ENABLED' in self.cpu_options and region in tdx_supported_regions:
        self.mem_encryption = 'TDX'
```
And of course this really applies to all CSPs as such this should really be lifted to the base class of the jobs. A bit more abstraction is needed for that. It's a bit bigger change but we need the same logic for all 3 CSPs. The requirement can be boiled down to selecting a specific instance type in a specific region when either TDX or SEV is set and run that instance with a specific flag. This is common across all 3 CSPs we support.

2024-05-31 09:22 UTC, apozsuse commented
Closing this PR as this will be implemented in the test refactor.

2024-05-31 09:22 UTC, closed without merging