Includes `download_type` parameter to select the type of download job
SUSE-Enceladus/mash pull request #875
Opened 2023-12-22 09:42 UTC by apozsuse

Renamed the file `mash/services/download/obs_build_result.py` to`obs_job.py` as Sean suggested. There only the class name has been changed. Additionally changed the old `obs_job.py` to `service.py`. 

That change in the names messed up with the diff :face_with_spiral_eyes: 

### What does this PR do? Why are we making this change?
### How will these changes be tested?
### How will this change be deployed? Any special considerations?
### Additional Information

2023-12-22 09:48 UTC, apozsuse commented
Changes in `mash/services/download/service.py`:
- Change the name of the class to `DownloadService`.
- Lines 248-251 includes `download_type` parameter to instantiate the approrpiate class:
```python
        if 'download_type' in job and job['download_type'] == 'S3':
            job_worker = S3DownloadJob(**kwargs)
        else:
            job_worker = OBSDownloadJob(**kwargs)
```

2023-12-22 09:49 UTC, apozsuse commented
Changes in `mash/services/download/obs_job.py`:
- Changes the class name to `OBSDownloadJob`

2023-12-22 18:00 UTC, rjschwei requested changes

2023-12-26 11:18 UTC, apozsuse commented on mash/services/api/v1/schema/jobs/__init__.py
> +            description='The type of download to get the source image file.'
Fixed!

2023-12-26 11:18 UTC, apozsuse commented on mash/services/api/v1/schema/jobs/__init__.py
> +                        ' in a AWS S3 bucket. '
Fixed

2024-01-02 17:05 UTC, smarlowucf approved these changes

2024-01-03 13:40 UTC, merged